### ISSUE TITLE
Legend in autographs() only prints categories as TRUE/FALSE

### ISSUE THREAD

**Issue by jaeltan** [stocnet/manynet#38]
The legend when plotting `diff_model` objects using the `autographs()` function shows the categories as 'TRUE' or 'FALSE' rather than 'Infected' or 'Susceptible' etc.

``` r
manynet::autographs(migraph:: play_diffusion(manynet::ison_adolescents, recovery = 0.2), node_color = "Infected") + ggplot2::guides(colour = ggplot2::guide_legend(""))
#> Registered S3 method overwritten by 'manynet':
#>   method          from     
#>   print.tbl_graph tidygraph
```

![](https://i.imgur.com/hUZpPE8.png)

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by henriquesposito** [comment]
This happens when we specify the node color, for example, when you run without specifying the legend appears correctly:

`manynet::autographs(migraph:: play_diffusion(manynet::ison_adolescents,
                                             recovery = 0.2)) + 
  ggplot2::guides(colour = ggplot2::guide_legend(""))`

This is a relatively simple fix but I am not sure it we should actually change this as a default behavior, what do you think @jaeltan? Thank you!

**Comment by jaeltan** [comment]
Hi @henriquesposito , thank you for looking into this! I see what you mean, I don't think there is a need to change that. But now the legend only prints for the red nodes, i.e. the 'Infected' nodes, but not for the blue/ 'Susceptible' nodes.

`manynet::autographs(migraph:: play_diffusion(manynet::ison_algebra, steps = 10)) + ggplot2::guides(colour = ggplot2::guide_legend(""))`

This happens with or without specifying the node colour... I've tried changing the screen size but it didn't change the legend, does this happen on your side?

**Comment by jhollway** [comment]
Good discussion. I think in general we could revisit how/when legends are displayed in the package. For `autographs()`, one single legend below or to the right side, where possible, would probably look best. But I would be happy to discuss/see options.

**Comment by henriquesposito** [comment]
Thank you both for your feedback. We now add and "collect" legends by default for diffusion plots in `autographs()`. Where possible, legends are now "collected" and only the longest legend appears to the right of the plots. For example, `autographs(migraph::play_diffusion(ison_adolescents))` now returns only one legend instead of two. 

![Image](https://github.com/snlab-ch/manynet/assets/69251755/5071cdd3-d166-485e-abbf-86b940faa251)
